name: Checks

on:
  pull_request_target:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: print ref
      run: echo ${{ github.base_ref }}
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Beep boop"
