name: Comment on PR triggered by comment

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'Bot!'
          reaction: rocket
          prefix_only: true
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
      - name: Dump GitHub context
        if: steps.check.outputs.triggered == 'true'
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout pr
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge
          path: pool
      - name: fetch master
        if: steps.check.outputs.triggered == 'true'
        run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin master:master
        working-directory: pool
      - name: print diff
        if: steps.check.outputs.triggered == 'true'
        run: git diff --name-only master
        working-directory: pool
      - name: checkout master
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v2
        with:
          path: master
      - name: create review
        if: steps.check.outputs.triggered == 'true'
        uses: ./master/.github/actions/horizon-pr-review
        with:
          pool: pool
      - name: print comment
        if: steps.check.outputs.triggered == 'true'
        run: cat comment.md
