name: Comment on PR

on:
  pull_request_target:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    container: horizoneda/horizon:latest
    steps:
    - name: install jq
      run: apt-get install jq
    - name: checkout master
      uses: actions/checkout@v2
      with:
        path: master
    - name: checkout pr
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/head
        path: pool
    - name: ls
      run: ls pool/parts/opto/led/cree/
    - name: fetch master
      run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin ${{ github.base_ref }}:${{ github.base_ref }}
      working-directory: pool
    - name: add pool
      run: python3 master/scripts/ci/add_pool.py
    - name: update pool
      run: python3 master/scripts/ci/update_pool.py >> comment.md
    - name: print diff to base
      run: python3 master/scripts/ci/diff_to_base.py ${{ github.base_ref }}  >> comment.md
    - name: print comment
      if: ${{ always() }}
      run: cat comment.md
    - name: comment
      run: |
        jq -n  --rawfile body comment.md '{"body":$body}' | curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header "Accept: application/vnd.github.v3+json" \
        --data -
