name: Comment on PR

on:
  pull_request_target:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout pr
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
        path: pool
    - name: fetch master
      run: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin master:master
      working-directory: pool

    - name: create review
      if: steps.check.outputs.triggered == 'true'
      uses: docker://horizoneda/horizon-pr-review:latest
      with:
        args: /github/workspace/pool -u -o /github/workspace/comment.md

    - name: comment
      run: |
        jq -R --slurp '{body: .}' comment.md | curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header "Accept: application/vnd.github.v3+json" \
        --data @-
